server:
  port: 10001


logging:
  level:
    org.springframework.cloud.consul: DEBUG

spring:
  application:
    name: consul-demo-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        serviceName: ${spring.application.name}