server:
  port: 10003


logging:
  level:
    org.springframework.cloud.consul: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
    gateway:
      routes:
      - id: user_route
        uri: http://127.0.0.1:10001
        order: 1000
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1

  zipkin:
    enabled: true
    sender:
      type: web
    base-url:  http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0