## Mybatis config
mybatis:
  type-aliases-package: com.jsjchai.model  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml


rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user-group
    send-message-timeout: 300000