## Mybatis config
mybatis:
  type-aliases-package: com.jsjchai.model  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.241.134:9876
      bindings:
        output:
          destination: test-topic
          content-type: application/json
        input:
          destination: test-topic
          content-type: application/json
          group: test-group